In [3]:
import scipy as sp
import pandas as pd
import numpy as np
from numpy import pi
from scipy import *
from matplotlib.pyplot import *
from scipy.linalg import *
from numpy.linalg import *
import scipy.sparse as sparse
from scipy.sparse.linalg import splu
from timeit import default_timer as timer
import AYOR as ay



#### To measure the digits of accuracy

In [16]:
##-np.log10(abs(x_computed-x_exact)/x_computed)

In [17]:
m = np.array([10,-32,0,3,-21])
np.sign(m)
##help(np.sign)

array([ 1, -1,  0,  1, -1])

$$
Horner's Rule
$$
$$
Polynomial
$$

In [18]:
c = [i for i in range(10)]##

In [19]:
ay.horner(c,2)

757

In [5]:
#Given the roots r, To get the coefficient of a polynomial
r = np.array([-2.0,-1,1,1,3,6])
c = np.poly(r)
c


array([  1.,  -8.,   6.,  44., -43., -36.,  36.])

In [6]:
c_co = np.poly1d(c)
#Given the coefficient of a polynomial,to get the roots
r_comp = np.sort(c_co.roots)
c_co

poly1d([  1.,  -8.,   6.,  44., -43., -36.,  36.])

In [7]:
r_comp

array([-2.        , -1.        ,  0.99999999,  1.00000001,  3.        ,
        6.        ])

In [8]:
c_comp = np.poly(r_comp)
c_comp

array([  1.,  -8.,   6.,  44., -43., -36.,  36.])

In [11]:
###-np.log10(abs(c_comp-c_co)/c_comp)

In [88]:
ay.quad( 1,-2,-3)

(3.0, -1.0)

##### Forward error is the difference between the exact solution or roots and the computed solution ( F(x)) OR the distance between the input the data


##### Backward error is  difference between the exact x value and the computed x OR the distance between the out the data

$$
f_e = \frac{|f(x) - fcal(x)|}{|f(x)|}
$$


$$
b_e = \frac{|x- xcal|}{|x|}
$$

A problem is said to be well conditioned if small change in the input lead to small change in the output.
#### Interpolating polynomial
To turn t values, years into vander matrix

In [25]:
t = np.array([1,2,3,4,5])
V = np.vander(t)
V

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [28]:
c = solve(V,t) 
c
#to solve for the constant
#construct a polynomisl with the constants


array([-9.25185854e-19, -8.32667268e-18,  1.31376391e-16,  1.00000000e+00,
        1.66533454e-16])

To get the shape of a matrix A

$A.shape$

You can concatenate 2 arrays using 
$np.hstack([A,A])$ ...for rows
$np.vstack([A,A])$ ...for coloumns


In [29]:
A =  np.array([list(np.arange(1,10,2)),[3,5,4,5,2],[1,2,3,4,5],list(np.linspace(1,20,5)),[1,4,6,4,7]])
A@A@A

array([[  931.      ,  2967.5625  ,  4448.375   ,  5165.6875  ,
         6681.      ],
       [  694.      ,  2228.6875  ,  3356.125   ,  3957.0625  ,
         5098.      ],
       [  552.      ,  1759.5     ,  2638.      ,  3068.5     ,
         3966.      ],
       [ 1973.25    ,  6289.734375,  9426.90625 , 10932.953125,
        14147.25    ],
       [  727.      ,  2275.      ,  3389.      ,  3971.      ,
         5089.      ]])

$C^T.C$ the transpose of C

In [32]:
AAA =3333

In [33]:
K = A.T@A
K@K

array([[  6642.875    ,  23618.40625  ,  37770.9375   ,  49787.46875  ,
         63493.       ],
       [ 23618.40625  ,  85149.1796875, 137005.453125 , 180886.7265625,
        231445.       ],
       [ 37770.9375   , 137005.453125 , 221028.96875  , 292046.484375 ,
        374196.       ],
       [ 49787.46875  , 180886.7265625, 292046.484375 , 386077.2421875,
        494809.       ],
       [ 63493.       , 231445.       , 374196.       , 494809.       ,
        634666.       ]])

To pick rows and coloumns $A[a:b, c:d]   slicing$

$B[start:stop:step]$

In [69]:
K[:1:-3]

array([[ 47., 190., 320., 426., 559.]])

In [73]:
K[::,3:]

array([[ 45.25  ,  47.    ],
       [157.6875, 190.    ],
       [251.125 , 320.    ],
       [338.5625, 426.    ],
       [426.    , 559.    ]])

to create a diagonal mitrix

In [86]:
#D =np.diag([1,2,3,4,5])
I = np.identity(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [89]:
A@K

array([[ 1024.5    ,  3731.625  ,  6031.75   ,  7977.875  , 10230.     ],
       [  654.     ,  2194.5    ,  3417.     ,  4473.5    ,  5619.     ],
       [  598.     ,  2160.75   ,  3480.5    ,  4598.25   ,  5886.     ],
       [ 2197.375  ,  8051.53125, 13047.6875 , 17271.84375, 22176.     ],
       [  861.     ,  3091.     ,  4960.     ,  6519.     ,  8344.     ]])

In [98]:
np.dot(A,I)

array([[ 1.  ,  3.  ,  5.  ,  7.  ,  9.  ],
       [ 3.  ,  5.  ,  4.  ,  5.  ,  2.  ],
       [ 1.  ,  2.  ,  3.  ,  4.  ,  5.  ],
       [ 1.  ,  5.75, 10.5 , 15.25, 20.  ],
       [ 1.  ,  4.  ,  6.  ,  4.  ,  7.  ]])

In [99]:
A@I

array([[ 1.  ,  3.  ,  5.  ,  7.  ,  9.  ],
       [ 3.  ,  5.  ,  4.  ,  5.  ,  2.  ],
       [ 1.  ,  2.  ,  3.  ,  4.  ,  5.  ],
       [ 1.  ,  5.75, 10.5 , 15.25, 20.  ],
       [ 1.  ,  4.  ,  6.  ,  4.  ,  7.  ]])

To create a matrix of random integers in Python, randint() function of the numpy module is used. This function is used for random sampling i.e. all the numbers generated will be at random and cannot be predicted at hand.

$Syntax :  numpy.random.randint(low, high=None, size=None, dtype=’l’)$

low : [int] Lowest (signed) integer to be drawn from the distribution.But, it works as a highest integer in the sample if high=None.
 
high : [int, optional] Largest (signed) integer to be drawn from the distribution.
 
size : [int or tuple of ints, optional] Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.
 
dtype : [optional] Desired output data-type.
Return : Array of random integers in the interval [low, high) or a single such random int if size not provided.

In [101]:
TA = np.random.randint(10, size=(2, 2))

In [103]:
TB = np.random.randint(10, size=(2, 2))

In [104]:
TB

array([[1, 6],
       [1, 5]])